spring:
  config:
    activate:
      on-profile: MongoDB
  data:
    mongodb:
      authentication-database: ${AUTHENTICATION_DATABASE:db-name}
      database: ${AUTHENTICATION_DATABASE:db-name}
      host: ${DATABASE_HOST:localhost}
      port: ${DATABASE_PORT:27017}
      username: ${DATABASE_USERNAME:db-username}
      password: ${DATABASE_PASSWORD:db-password}

basyx:
  backend: MongoDB
  aasdiscoveryservice:
    mongodb:
      collectionName: ${AUTHENTICATION_DATABASE:db-name}



registry:
  type: MongoDB
  discovery:
    enabled: true