basyx:
    aasdiscoveryservice:
        mongodb:
            collectionName: aasregistry
    backend: MongoDB
    cors:
        allowed-methods: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
        allowed-origins: '*'
management:
    endpoints:
        web:
            exposure:
                include: health,metrics,mappings


registry:
    type: MongoDB
    discovery:
        enabled: true

server:
    port: 8081
spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: BaSyx Digital Twin Registry
    data:
        mongodb:
            authentication-database: aasregistry
            database: aasregistry
            host: localhost
            password: smartsystemshubdatabaseforfactoryX
            port: 27017
            username: smartsystemhub
    profiles:
        active: logEvents,MongoDB

description:
    profiles: https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-001


logging:
    level:
        root: TRACE
        org.eclipse.digitaltwin.basyx: TRACE
        org.springframework: TRACE

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
        csrf:
            enabled: false
