basyx.backend=InMemory
registry.type=InMemory
registry.discovery.enabled=true

spring.config.activate.on-profile=InMemory

spring.autoconfigure.exclude=org.springframework.boot.mongodb.autoconfigure.MongoAutoConfiguration,org.springframework.boot.data.mongodb.autoconfigure.DataMongoAutoConfiguration
