version: '3.6'

networks:
  basyx-submodel:
    internal: false
  mongo-submodel:
    internal: false

volumes:
  zookeeper-data:
    driver: local
  zookeeper-log:
    driver: local
  kafka-data:
    driver: local
  mongodb-data-5.0.10:
    driver: local
  submodel-config:
     
services:  
  portainer:
    image: portainer/portainer-ce:2.0.1
    container_name: portainer
    restart: always
    ports:
      - "9091:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - basyx-submodel
      
  zookeeper:
    image: zookeeper:3.6
    container_name: zookeeper
    restart: always
    ports:
      - "2182:2181"  
    volumes:  
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log   
    networks:
      - basyx-submodel
     
  kafka:
    image: confluentinc/cp-kafka:6.2.1
    container_name: kafka
    volumes:
      - kafka-data:/var/lib/kafka
    ports:
      - "9093:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    links:
      - zookeeper
    restart: always
    networks:
      - basyx-submodel
  
  akhq:
    image: tchiotludo/akhq:0.24.0
    container_name: akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:29092"
    ports:
      - 8087:8080
    restart: always
    depends_on:
      - kafka
    networks:
      - basyx-submodel

  mongodb:
    image: mongo:5.0.10
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27018:27017
    volumes:
      - mongodb-data-5.0.10:/data/db
    networks:
      - basyx-submodel
   
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
    ports:
      - "0.0.0.0:8082:8081"
    networks:
      - basyx-submodel
    restart: always
    depends_on:
      - mongodb  
               
  submodel-registry-kafka-mongodb:
    image: submodel-registry-test/submodel-registry-kafka-mongodb:2.0.0-SNAPSHOT
    container_name: submodel-registry-kafka-mongodb
    pull_policy: never
    ports:
      - "8024:8080"
    depends_on:
      - mongodb
      - kafka
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017
    networks:
      - basyx-submodel


  submodel-registry-kafka-mongodb-different-port-path:
    image: submodel-registry-test/submodel-registry-kafka-mongodb:2.0.0-SNAPSHOT
    container_name: submodel-registry-kafka-mongodb-different-port-path
    pull_policy: never
    ports:
      - "8025:8091"
    depends_on:
      - mongodb
      - kafka
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017
      SERVER_PORT: "8091"
      SERVER_SERVLET_CONTEXT_PATH: /api/v3.0.1/    
    networks:
      - basyx-submodel

  submodel-registry-kafka-mem:
    image: submodel-registry-test/submodel-registry-kafka-mem:2.0.0-SNAPSHOT
    container_name: submodel-registry-kafka-mem
    pull_policy: never
    ports:
      - "8035:8080"
    depends_on:
      - kafka
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
    networks:
      - basyx-submodel

  submodel-registry-kafka-mem-different-port-path:
    image: submodel-registry-test/submodel-registry-kafka-mem:2.0.0-SNAPSHOT
    container_name: submodel-registry-kafka-mem-different-port-path
    pull_policy: never
    ports:
      - "8036:8091"
    depends_on:
      - kafka
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SERVER_PORT: "8091"
      SERVER_SERVLET_CONTEXT_PATH: /api/v3.0.1/  
    networks:
      - basyx-submodel

  submodel-registry-log-mem:
    image: submodel-registry-test/submodel-registry-log-mem:2.0.0-SNAPSHOT
    container_name: submodel-registry-log-mem
    pull_policy: never
    ports:
      - "8043:8080"
    restart: always
    networks:
      - basyx-submodel

  submodel-registry-log-mem-different-port-path:
    image: submodel-registry-test/submodel-registry-log-mem:2.0.0-SNAPSHOT
    container_name: submodel-registry-log-mem-different-port-path
    pull_policy: never
    ports:
      - "8044:8091"
    restart: always
    environment:
      SERVER_PORT: "8091"
      SERVER_SERVLET_CONTEXT_PATH: /api/v3.0.1/ 
    networks:
      - basyx-submodel

  submodel-registry-log-mongodb:
    image: submodel-registry-test/submodel-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name: submodel-registry-log-mongodb
    pull_policy: never
    ports:
      - "8053:8080"
    depends_on:
      - mongodb
    restart: always
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017
    networks:
      - basyx-submodel


  submodel-registry-log-mongodb-different-port-path:
    image: submodel-registry-test/submodel-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name: submodel-registry-log-mongodb-different-port-path
    pull_policy: never
    ports:
      - "8054:8091"
    depends_on:
      - mongodb
    restart: always
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017
      SERVER_PORT: "8091"
      SERVER_SERVLET_CONTEXT_PATH: /api/v3.0.1/ 
    networks:
      - basyx-submodel
