---
events:
  sink:
description:
  profiles: https://admin-shell.io/aas/API/3/0/SubmodelRegistryServiceSpecification/SSP-001
springdoc:
   api-docs:
      path: /api-docs
springfox:
  documentation:
    enabled: true
  #  open-api.v3.path: /api-docs
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
logging:
  level:
    root: INFO
server:
  shutdown: graceful
    # Do NOT change any port while running in a Docker container.
    # Changing this will make the service unreachable from outside the container.
    # This port should only be changed when running the application without Docker
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: Basyx Submodel Registry
  jackson:
    date-format: org.eclipse.digitaltwin.basyx.submodelregistry.service.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false         