version: '3.6'

networks:
  basyx:
    internal: false
  mongo:
    internal: false

volumes:
  zookeeper-data:
    driver: local
  zookeeper-log:
    driver: local
  kafka-data:
    driver: local
  mongodb-data-5.0.10:
    driver: local
  aas-config:
     
services:  
  portainer:
    image: portainer/portainer-ce:2.0.1
    container_name: portainer
    restart: always
    ports:
      - "9090:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - basyx
      
  zookeeper:
    image: zookeeper:3.6
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"  
    volumes:  
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log   
    networks:
      - basyx
     
  kafka:
    image: confluentinc/cp-kafka:6.2.1
    container_name: kafka
    volumes:
      - kafka-data:/var/lib/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    links:
      - zookeeper
    restart: always
    networks:
      - basyx
  
  akhq:
    image: tchiotludo/akhq:0.24.0
    container_name: akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:29092"
    ports:
      - 8086:8080
    restart: always
    depends_on:
      - kafka
    networks:
      - basyx

  mongodb:
    image: mongo:5.0.10
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongodb-data-5.0.10:/data/db
    networks:
      - basyx
   
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - basyx
    depends_on:
      - mongodb   
               
  aas-registry-kafka-mongodb:
    image: aas-registry-test/aas-registry-kafka-mongodb:2.0.0-SNAPSHOT
    container_name: aas-registry-kafka-mongodb
    pull_policy: never
    ports:
      - "8020:8080"
    depends_on:
      - mongodb
      - kafka
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017
    networks:
      - basyx

  aas-registry-kafka-mongodb-different-port-path:
    image: aas-registry-test/aas-registry-kafka-mongodb:2.0.0-SNAPSHOT
    container_name: aas-registry-kafka-mongodb-different-port-path
    pull_policy: never
    ports:
      - "8021:8091"
    depends_on:
      - mongodb
      - kafka
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017
      SERVER_PORT: "8091"
      SERVER_SERVLET_CONTEXT_PATH: /api/v3.0.1/
    networks:
      - basyx

  aas-registry-kafka-mongodb-external-conf:
    image: aas-registry-test/aas-registry-kafka-mongodb:2.0.0-SNAPSHOT
    container_name: aas-registry-kafka-mongodb-external-conf
    pull_policy: never
    ports:
      - "8024:8080"
    depends_on:
      - kafka
      - mongodb
    restart: always    
    volumes: 
      # additional header configs for cors
      - ./aas-config:/workspace/config  # /workspace is the docker file working dir
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
    networks:
      - basyx

  aas-registry-kafka-mem:
    image: aas-registry-test/aas-registry-kafka-mem:2.0.0-SNAPSHOT
    container_name: aas-registry-kafka-mem
    pull_policy: never
    ports:
      - "8030:8080"
    depends_on:
      - kafka
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
    networks:
      - basyx
  
  aas-registry-kafka-mem-different-port-path:
    image: aas-registry-test/aas-registry-kafka-mem:2.0.0-SNAPSHOT
    container_name: aas-registry-kafka-mem-different-port-path
    pull_policy: never
    ports:
      - "8031:8090"
    depends_on:
      - kafka
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SERVER_PORT: "8090"
      SERVER_SERVLET_CONTEXT_PATH: /api/v3.0.1/
    networks:
      - basyx

  aas-registry-log-mem:
    image: aas-registry-test/aas-registry-log-mem:2.0.0-SNAPSHOT
    container_name: aas-registry-log-mem
    pull_policy: never
    ports:
      - "8040:8080"
    restart: always
    networks:
      - basyx

  aas-registry-log-mem-different-port-path:
    image: aas-registry-test/aas-registry-log-mem:2.0.0-SNAPSHOT
    container_name: aas-registry-log-mem-different-port-path
    pull_policy: never
    ports:
      - "8066:8099"
    environment:
      SERVER_PORT: "8099"
      SERVER_SERVLET_CONTEXT_PATH: /api/v3.0.1
    restart: always
    networks:
      - basyx

  aas-registry-log-mongodb:
    image: aas-registry-test/aas-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name: aas-registry-log-mongodb
    pull_policy: never
    ports:
      - "8050:8080"
    depends_on:
      - mongodb
    restart: always
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017
    networks:
      - basyx

  aas-registry-log-mongodb-different-port-path:
    image: aas-registry-test/aas-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name: aas-registry-log-mongodb-different-port-path
    pull_policy: never
    ports:
      - "8051:8060"
    depends_on:
      - mongodb
    restart: always
    environment:
      SERVER_PORT: "8060"
      SERVER_SERVLET_CONTEXT_PATH: /api/v3.0.1
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017
    networks:
      - basyx  
