basyx:
  aasdiscoveryservice:
  cors:
    allowed-methods: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
    allowed-origins: '*'


  aasregistry:
    feature:
      aasdigitaltwinregistry:
        enabled: true

  endpoints:
    web:
      exposure:
        include: health,metrics,mappings

server:
  port: 8081

spring:
  profiles:
    active: logEvents,${SPRING_PROFILE:InMemory}
  main:
    allow-bean-definition-overriding: true
  application:
    name: BaSyx Digital Twin Registry

digitaltwinregistry:
  enabled: true


description:
  profiles: https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-001,
    https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-002,
    https://admin-shell.io/aas/API/3/0/DiscoveryServiceSpecification/SSP-001

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
    org.eclipse.digitaltwin.basyx: ${LOGGING_LEVEL:INFO}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    csrf:
      enabled: false