basyx:
  submodelservice: 
    feature:
      operation:
        dispatcher:
          mappings:
            SquareOperation: SquareOperation
            BasicOperations.AddOperation: basic.ops.AddOperation
            BasicOperations.HelloOperation: HelloOperation