basyx:
  operation:
    invokation:
      mappings:
        SquareOperation: SquareOperation
        BasicOperations.AddOperation: basic.ops.AddOperation
        BasicOperations.HelloOperation: HelloOperation