basyx:
  backend: InMemory
  submodelservice:
    submodel:
      file: submodel.json
    feature:
      operation:
        dispatcher:
          enabled: true
          mappings: 
            SquareOperation: SquareOperation
            "BasicOperations.AddOperation": basic.ops.AddOperation
            BasicOperations.HelloOperation: HelloOperation
          java:
            sources: sources
            classes: classes
            additionalClasspath: 
            - jars/HelloWorld.jar