networks:
  auth:
    driver: bridge

services:

  # nginx reverse proxy to support dns lookup
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.6.0-alpine
    container_name: proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: keycloak.basyx.localhost
    networks:
      - auth

  submodel-service:
    image: eclipsebasyx/submodel-service:${REVISION}
    container_name: submodel-service
    pull_policy: missing
    environment:
      # add the mounted jar file file:submodel.json or submodel.json
      BASYX_SUBMODELSERVICE_SUBMODEL_FILE: submodel.json
      # we add all sources -> they will be compiled on startup
      BASYX_SUBMODELSERVICE_FEATURE_OPERATION_DISPATCHER_JAVA_SOURCES: sources
      # this is the jar file
      BASYX_SUBMODELSERVICE_FEATURE_OPERATION_DISPATCHER_JAVA_ADDITIONALCLASSPATH: jars/HelloWorld.jar
      # we specify the mappings in the application-mappings.yml
      SPRING_PROFILES_ACTIVE: mappings
    ports:
      - ${PORT}:8081
    volumes:
      - ./submodel.json:/application/submodel.json:ro
      - ./sources/:/application/sources/:ro
      - ./jars/HelloWorld.jar:/application/jars/HelloWorld.jar:ro
      - ./application-mappings.yml:/application/config/application-mappings.yml/:ro

  submodel-service-auth:
    image: eclipsebasyx/submodel-service:${REVISION}
    container_name: submodel-service-auth
    pull_policy: missing    
    extra_hosts:
    - "keycloak.basyx.localhost:host-gateway"
    environment:
      # add the mounted jar file file:submodel.json or submodel.json
      BASYX_SUBMODELSERVICE_SUBMODEL_FILE: submodel.json
      # we add all sources -> they will be compiled on startup
      BASYX_SUBMODELSERVICE_FEATURE_OPERATION_DISPATCHER_JAVA_SOURCES: sources
      # this is the jar file
      BASYX_SUBMODELSERVICE_FEATURE_OPERATION_DISPATCHER_JAVA_ADDITIONALCLASSPATH: jars/HelloWorld.jar
      # we specify the mappings in the application-mappings.yml
      # and rbac related things in application-security.yml
      SPRING_PROFILES_ACTIVE: mappings,rbac
    ports:
      - ${PORT_AUTH}:8081
    volumes:
      - ./auth/rbac_rules.json:/application/rbac_rules.json:ro
      - ./auth/application-rbac.yml:/application/config/application-rbac.yml/:ro
      - ./submodel.json:/application/submodel.json:ro
      - ./sources/:/application/sources/:ro
      - ./jars/HelloWorld.jar:/application/jars/HelloWorld.jar:ro
      - ./application-mappings.yml:/application/config/application-mappings.yml/:ro
    networks:
      - auth
    depends_on:
      keycloak-healthcheck:
        condition: service_completed_successfully

  keycloak:
    image: keycloak/keycloak:24.0.4
    container_name: keycloak
    environment:
      VIRTUAL_HOST: keycloak.basyx.localhost
      VIRTUAL_PORT: "8080"
      KC_HOSTNAME: keycloak.basyx.localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak-admin
      KC_HTTP_ENABLED: "true"
      KC_HTTPS_ENABLED: "false"
      KC_HEALTH_ENABLED: "true"
      KC_IMPORT: /opt/keycloak/data/import/
    command: ["start-dev", "--import-realm"]
    ports:
      - 9097:8080
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
    networks:
      - auth   
      
  keycloak-healthcheck:
    image: curlimages/curl:latest
    command: >
      sh -c "
        echo 'Waiting for Keycloak to become ready...';
        until curl -sf http://keycloak:8080/health/ready; do
          sleep 5;
        done;
        echo 'Keycloak is ready!'"
    depends_on:
      - keycloak
    networks:
      - auth
