server.port=8081
spring.application.name=AAS Discovery Service
basyx.aasdiscoveryservice.name=aas-discovery-service

basyx.backend=MongoDB

spring.mongodb.host=mongo
spring.mongodb.database=aas-discovery
spring.mongodb.authentication-database=admin
spring.mongodb.username=mongoAdmin
spring.mongodb.password=mongoPassword

basyx.cors.allowed-origins=*
basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD