---
basyx:
  cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD"

spring:
  mongodb:
    database: aas-registry
    uri: mongodb://mongoAdmin:mongoPassword@mongo:27017
