image: 
  name: eclipsebasyx/aas-gui:v2-240125
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

config:
  aasRepoUrl: "aas-environment:8080/shells"
  aasSubmodelsRepoUrl: "aas-environment:8080/submodels"
  conceptdescriptionRepoUrl: "aas-environment:8080/concept-descriptions"
  aasDiscoveryUrl: "aas-discovery:8080/lookup/shells"
  aasRegistryUrl: "aas-registry:8080/shell-descriptors"
  submodelRegistryUrl: "sm-registry:8080/submodel-descriptors"
  keycloakUrl: https://keycloak.basyx.local
  keycloakRealm: BaSyx
  keycloakClientId: basyx-web-ui

logo:
  relativePath: null
externalPlugins:
  enabled: false
  # Only supporting ConfigMaps for now, but could also support GitRepos, Secrets, Links and/or volumes.
  # plugins:
  # - fileName: TimeSeriesVisualizer.vue
  #   configMapName: plugin-1
  # - fileName: SineVisualizer.vue
  #   configMapName: plugin-2

ingress:
  enabled: false
  host: aas-web-ui.local

apirule:
  enabled: false
  host: aas-web-ui.local
  methods: 
      - "GET" 
      - "HEAD" 
      - "POST" 
      - "PUT" 
      - "DELETE" 
      - "CONNECT" 
      - "OPTIONS" 
      - "TRACE"
      - "PATCH"
  # -- Allows configuring CORS headers sent with the response. If corsPolicy is not defined, the CORS headers are enforced to be empty.
  corsPolicy: 
    allowMethods:
    - POST
    - GET
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
    - HEAD
    allowOrigins:
      - regex: ".*" # allow all origins
    allowCredentials: true