/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.eclipse.digitaltwin.basyx.aasregistry.service.api;

import org.eclipse.digitaltwin.basyx.aasregistry.model.Result;
import org.eclipse.digitaltwin.basyx.aasregistry.model.ServiceDescription;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-11-26T10:50:35.975734200+01:00[Europe/Berlin]")
@Validated
@Controller
@Tag(name = "Registry and Discovery Interface", description = "the Registry and Discovery Interface API")
public interface DescriptionApi {

    default DescriptionApiDelegate getDelegate() {
        return new DescriptionApiDelegate() {};
    }

    /**
     * GET /description : Returns the self-describing information of a network resource (ServiceDescription)
     *
     * @return Requested Description (status code 200)
     *         or Forbidden (status code 403)
     *         or Default error handling for unmentioned status codes (status code 200)
     */
    @Operation(
        operationId = "getDescription",
        summary = "Returns the self-describing information of a network resource (ServiceDescription)",
        tags = { "Registry and Discovery Interface" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Requested Description", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ServiceDescription.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Result.class))
            }),
            @ApiResponse(responseCode = "default", description = "Default error handling for unmentioned status codes", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Result.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/description",
        produces = { "application/json" }
    )
    default ResponseEntity<ServiceDescription> getDescription(
        
    ) {
        return getDelegate().getDescription();
     }

}
