package org.eclipse.digitaltwin.basyx.aasregistry.model;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import org.eclipse.digitaltwin.basyx.aasregistry.model.DataSpecificationIec61360;
import org.eclipse.digitaltwin.basyx.aasregistry.model.DataTypeIec61360;
import org.eclipse.digitaltwin.basyx.aasregistry.model.LangStringDefinitionTypeIec61360;
import org.eclipse.digitaltwin.basyx.aasregistry.model.LangStringPreferredNameTypeIec61360;
import org.eclipse.digitaltwin.basyx.aasregistry.model.LangStringShortNameTypeIec61360;
import org.eclipse.digitaltwin.basyx.aasregistry.model.LevelType;
import org.eclipse.digitaltwin.basyx.aasregistry.model.Reference;
import org.eclipse.digitaltwin.basyx.aasregistry.model.ValueList;
import org.openapitools.jackson.nullable.JsonNullable;
import java.io.Serializable;
import java.time.OffsetDateTime;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import jakarta.annotation.Generated;


@JsonIgnoreProperties(
  value = "modelType", // ignore manually set modelType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the modelType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "modelType", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = DataSpecificationIec61360.class, name = "DataSpecificationIec61360")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-11-26T10:50:20.873153600+01:00[Europe/Berlin]")
public interface DataSpecificationContent extends Serializable {
    public String getModelType();
}
