apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sm-registry.fullname" . }}-config
  labels:
    {{- include "sm-registry.labels" . | nindent 4 }}
data:
  application.yaml: |-
    {{ .Values.config | nindent 4 }}