apiVersion: v2
name: aas-basyx-v2-full
description: Umbrella chart for the AAS Basyx v2 Environment
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
# Contains frontend, backend and dashboard
- name: aas-registry
  version: "0.0.1"
  repository: file://dependency_charts/aas-registry
  condition: aas-registry.enabled
- name: sm-registry
  version: "0.0.1"
  repository: file://dependency_charts/sm-registry
  condition: sm-registry.enabled
- name: aas-discovery
  version: "0.0.1"
  repository: file://dependency_charts/aas-discovery
  condition: aas-discovery.enabled
- name: aas-environment
  version: "0.0.1"
  repository: file://dependency_charts/aas-environment
  condition: aas-environment.enabled
- name: aas-web-ui
  version: "0.0.1"
  repository: file://dependency_charts/aas-web-ui
  condition: aas-web-ui.enabled
- name: mongodb
  version: "14.5.0"
  repository: https://charts.bitnami.com/bitnami
  alias: mongodb
  condition: mongodb.enabled
  # Isolation der MongoDB-Variablen durch eigenen Namespace
  namespace: project-factory-x
- repository: https://charts.bitnami.com/bitnami
  name: keycloak
  version: 24.4.11
  condition: keycloak.enabled

# MongoDB has an issue with charts not sitting well in an umbrella chart.
# This is a bug with some common variables being defined externally.
# Check README.md or install.sh for commands to deploy this separately.
# - name: mongodb
#   version: "14.5.0"
#   repository: https://charts.bitnami.com/bitnami

# External images from open-source helm charts
# - name: mosquitto
#   version: 2.4.1
#   repository: https://storage.googleapis.com/t3n-helm-charts
# - name: kafka
#   version: 22.1.3
#   repository: https://charts.bitnami.com/bitnami
# - name: influxdb
#   version: 5.6.1
#   repository: https://charts.bitnami.com/bitnami
# - name: grafana
#   version: "9.6.6"
#   repository: https://charts.bitnami.com/bitnami
